# ~/.bash_aliases
alias grep='grep --color=auto'
alias h='history | tail'
alias hg='history | grep'
alias recall='history | grep'
alias l='ls -CF' 
alias l.='ls -d .*' 
alias la='ls -A' 
alias ll='ls -alF' 
alias ls='ls --color=auto' 
alias lsd='ls -d .*' 
alias lt='ls -altr' 
alias mv='mv -i' 
#alias rl='cd ~/Dropbox_not_syncd/98_2011/webs/apps/linker'
alias rvm-restart='source '\''/home/durrantm/.rvm/scripts/rvm'\'''
alias s='cd ..'
alias src='script/rails console'
alias srdc='script/rails destroy controller'
alias srdm='script/rails destroy model'
alias srds='script/rails destroy scaffold'
alias srgc='script/rails generate controller'
alias srgm='script/rails generate model'
alias srgs='script/rails generate scaffold'
alias srs='script/rails server'
#
alias webs='cd ~/Dropbox_not_syncd/webs/'
alias work='cd ~/Dropbox/98_2011/work/'
alias zap='rm -i'
alias raked='rake db:drop db:create db:migrate db:seed' 
#
alias rubyquiz='cd ~/Dropbox/98_2011/work/ruby_and_rails/ruby_quiz'
#
alias code='cd ~/Dropbox/98_2011/work/ruby_and_rails/code/'
alias setups='cd ~/Dropbox/98_2011/work/setups/'
alias docs='cd ~/Dropbox/98_2011/work/setups/'
# git
alias gstatus='git status '
alias gadd='git add '
alias gcommit='git commit'
alias gpull='git pull '
alias gpush='git push '
